### PR TITLE
Add display flexibility

### PR DESCRIPTION
**Pull request by pushchris**
Currently after the picker is displayed it is very stiff and doesn't expose much or allow itself to be changed. I've added some helper methods to allow for the tableview to be reloaded, for the user to know if the picker is visible on the screen, and to show the picker inside of a subview

### CODE REVIEW

**Comment by chenzeyu** [comment]
I'll look into it. Thanks!

**Comment by chenzeyu** [comment]
Hi, can you provide a demo with show in container?

**Comment by pushchris** [comment]
@chenzeyu I have added an example of when show in container would be useful: having it display below a navigation bar, but on top of other content.

**Comment by chenzeyu** [comment]
Thanks, let me look into it.

**Pull request merged**
